; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; The "Secret Sauce" that made your other project work
board_upload.maximum_size = 131072

lib_deps = 
    https://github.com/micro-ROS/micro_ros_arduino.git

build_flags =
    -D SERIAL_UART_INSTANCE=1
    -L .pio/libdeps/bluepill_f103c8/micro_ros_arduino/src/cortex-m3/
    -l microros
    ; Optimization flags to save RAM
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

upload_protocol = serial
upload_port = /dev/ttyUSB0
upload_speed = 115200