; GANTI NAMA ENV JIKA DIINGINKAN
[env:<platform_io_env>1]



platform = ststm32
board = bluepill_f103c8
framework = arduino

; The "Secret Sauce" that made your other project work
board_upload.maximum_size = 131072

lib_deps = 
    https://github.com/micro-ROS/micro_ros_arduino.git

build_flags =
    -D SERIAL_UART_INSTANCE=1
    -L .pio/libdeps/bluepill_f103c8/micro_ros_arduino/src/cortex-m3/
    -l microros
    ; Optimization flags to save RAM
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

upload_protocol = serial
upload_port = /dev/ttyUSB0 #<-- sesuaikan port untuk board 1
upload_speed = 115200

build_src_filter = +<main2.cpp> # <--- sesuaikan dengan main file board 2

; GANTI NAMA ENV JIKA DIINGINKAN <-- ini untuk double board
[env:<platform_io_env2>]

platform = ststm32
board = bluepill_f103c8
framework = arduino\
board_upload.maximum_size = 131072


build_src_filter = +<stm_counter.cpp> # <--- sesuaikan dengan main file board 1

lib_deps = 
    https://github.com/micro-ROS/micro_ros_arduino.git

build_flags =
    -D SERIAL_UART_INSTANCE=1
    -L .pio/libdeps/bluepill_f103c8/micro_ros_arduino/src/cortex-m3/
    -l microros
    ; Optimization flags to save RAM
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

upload_protocol = serial
; upload_port = /dev/ttyUSB0 <-- sesuaikan port untuk board 2
upload_speed = 115200